In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df_train = pd.read_csv('fall_train.csv',index_col='id')
df_train.head()

TIME        SL       EEG  BP   HR  CIRCLUATION  FALL
id                                                             
11742   8560.23  30913.00 -3620.000  68  169         1631     0
8789    4355.00   2254.61  -995.567  22   54          165     0
7933   15175.00  80259.60 -7051.030  75  320         3466     0
8578    4899.97   2853.85 -1280.160  52   67          224     1
14515   4247.03   2239.69  -922.626  47   51          132     1

In [ ]:
df_train.info

<bound method DataFrame.info of            TIME        SL       EEG  BP   HR  CIRCLUATION  FALL
id                                                             
11742   8560.23  30913.00 -3620.000  68  169         1631     0
8789    4355.00   2254.61  -995.567  22   54          165     0
7933   15175.00  80259.60 -7051.030  75  320         3466     0
8578    4899.97   2853.85 -1280.160  52   67          224     1
14515   4247.03   2239.69  -922.626  47   51          132     1
...         ...       ...       ...  ..  ...          ...   ...
13123   4034.87   1376.00  -646.000  15   54          101     0
3264   12259.40  74795.20 -4110.000  30  249         3630     0
9845    9824.58  29307.00 -4500.000  95  172         1518     0
10799  13541.50  72357.10 -4800.300  75  262         3211     0
2732    5377.27   4291.84  -906.000  15   88          292     0

[11467 rows x 7 columns]>

In [ ]:
y = df_train.FALL
x = df_train.drop(columns=['FALL'])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
# Apply standard scaling to get optimized result
ss = StandardScaler()
#sc = MinMaxScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

In [ ]:
x_train

array([[-0.13815344, -0.22448801,  0.01856335, -0.60901741,  0.02349561,
        -0.06371852],
       [-1.30008857, -0.56314458,  0.03610735, -0.93612945, -1.1413512 ,
        -0.70792449],
       [-0.06414387, -0.37976847,  0.00866419, -0.85435144, -0.18967897,
        -0.41442723],
       ...,
       [ 2.40833866,  1.44292456, -0.0226194 ,  0.96520924,  2.4673899 ,
         1.39170976],
       [-0.79146451, -0.4712668 ,  0.03262121, -0.67035092, -0.89010973,
        -0.54424332],
       [ 1.2530489 ,  0.53278273, -0.00697315,  1.08787625,  1.13504877,
         0.74955623]])

# Proceed with Modelling. We will use the following algorithms and check for best accuracy:

##  1. Logistic Regression  
0.78
##  2. Decision Trees  
0.8
##  3. K-Nearest Neighbors  
0.8049985
##  4. Naive Bayes  
0.29
##  5. Random Forests
##  6. Support Vector Machines
##  7. Stochastic Gradient Decent Classifier

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x_test)
accuracy_score(y_test, y_pred)

0.8049985469340308

#Load the testset

In [ ]:
df_test = pd.read_csv('fall_test.csv', index_col='id')
df_test.head()

TIME         SL       EEG   BP   HR  CIRCLUATION
id                                                         
3180   13814.30   67074.60  -3110.00   49  224         2192
12289  25836.50  496778.00 -16870.00  136  640        16053
7535    9796.62   43080.00  -3017.00  262  191         2254
598     8735.98   27778.90  -2826.17   94  156         1521
5136    6952.75    6799.33  -1210.00   27  119          395

In [ ]:
df_test1 = ss.transform(df_test)

##Apply our model on the test

In [ ]:
test_y = model.predict(df_test1)
test_y

array([1, 0, 0, ..., 0, 0, 0])

#Construct the submission

In [ ]:
df_test.index #just for check

Int64Index([ 3180, 12289,  7535,   598,  5136, 10760,  3909,  5619, 13297,
             3266,
            ...
             8961, 15732,  3210,  1484, 14594,  4070,   728,  7109, 10912,
             2708],
           dtype='int64', name='id', length=4915)

In [ ]:
submission = pd.DataFrame(
    {'id':df_test.index, 
     'FALL': test_y}
)
submission.head()

id  FALL
0   3180     1
1  12289     0
2   7535     0
3    598     0
4   5136     0

In [ ]:
submission.to_csv('knn.csv', index=None)

#Check vs Logistic
**0.78**

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr_predict = lr.predict(x_test)

# Print confusion matrix and accuracy score
lr_acc_score = accuracy_score(y_test, lr_predict)
print('Accuracy Score :', '%.2f' %lr_acc_score)

Accuracy Score : 0.78


##Check with Decision Tree
**0.809**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics 
tree_model = DecisionTreeClassifier(criterion = 'gini', max_depth = 10)
tree_model.fit(x_train, y_train)
y_pred = tree_model.predict(x_test)
acc = metrics.accuracy_score(y_test, y_pred)
print(acc)

0.8076140656785818


##Naive Baye

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
nb_predict = nb.predict(x_test)
nb_acc_score = accuracy_score(y_test, nb_predict)
print('Accuracy Score :', '%.2f' %nb_acc_score)

Accuracy Score : 0.29


##SVC

In [ ]:
from sklearn.svm import SVC
svc = SVC(random_state = 0, kernel='poly', degree=3, probability=True)
svc.fit(x_train,y_train)
svc_predict = svc.predict(x_test)
svc_acc_score = accuracy_score(y_test, svc_predict)
print('Accuracy Score :','%.2f' %svc_acc_score)

Accuracy Score : 0.78


In [ ]:
# Perform SGDC
from sklearn.linear_model import SGDClassifier
sgdc = SGDClassifier()
sgdc.fit(x_train,y_train)
sgdc_predict = sgdc.predict(x_test)
sgdc_acc_score = accuracy_score(y_test, sgdc_predict)
print('Accuracy Score :','%.2f' %sgdc_acc_score)

Accuracy Score : 0.78


#the best score from Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [ ]:
rf = RandomForestClassifier(random_state = 42)
from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [ ]:
#create a parameter grid to sample from during fitting:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)


{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [ ]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(x_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:  4.8min
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed: 20.1min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 36.5min finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [ ]:
rf_random.best_params_

{'bootstrap': True,
 'max_depth': None,
 'max_features': 'auto',
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 1800}

In [ ]:
#model
rf = RandomForestClassifier(bootstrap=True,
                            max_depth=None,
                            max_features='auto',
                            min_samples_leaf=2,
                            min_samples_split=2,
                            n_estimators=1800)
rf.fit(x_train,y_train)
rf_predict = rf.predict(x_test)
# Print confusion matrix and accuracy score
rf_acc_score = accuracy_score(y_test, rf_predict)
print('Accuracy Score :','%.2f' %rf_acc_score)

Accuracy Score : 0.85


In [ ]:
df_test = pd.read_csv('fall_test.csv', index_col='id')
df_test.head()

TIME         SL       EEG   BP   HR  CIRCLUATION
id                                                         
3180   13814.30   67074.60  -3110.00   49  224         2192
12289  25836.50  496778.00 -16870.00  136  640        16053
7535    9796.62   43080.00  -3017.00  262  191         2254
598     8735.98   27778.90  -2826.17   94  156         1521
5136    6952.75    6799.33  -1210.00   27  119          395

In [ ]:
df_test_RF = ss.transform(df_test)

##Apply our model on the test

In [ ]:
test_y = model.predict(df_test_RF)
test_y

array([1, 0, 0, ..., 0, 0, 0])

#Construct the submission

In [ ]:
df_test.index #just for check

Int64Index([ 3180, 12289,  7535,   598,  5136, 10760,  3909,  5619, 13297,
             3266,
            ...
             8961, 15732,  3210,  1484, 14594,  4070,   728,  7109, 10912,
             2708],
           dtype='int64', name='id', length=4915)

In [ ]:
submission = pd.DataFrame(
    {'id':df_test.index, 
     'FALL': test_y}
)
submission.head()

id  FALL
0   3180     1
1  12289     0
2   7535     0
3    598     0
4   5136     0

In [ ]:
submission.to_csv('RandomForest_085acc.csv', index=None)